# Generated by Django 5.2 on 2025-05-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='included',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PointList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.ManyToManyField(related_name='point_lists', to='trasy.point')),
            ],
        ),
    ]
