# Generated by Django 5.2 on 2025-05-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasy', '0003_pointlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(default=1, upload_to='background/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
