# Generated by Django 5.2 on 2025-05-07 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasy', '0004_backgroundimage_image_alter_backgroundimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointlist',
            name='backgroundImage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trasy.backgroundimage'),
            preserve_default=False,
        ),
    ]
