# Generated by Django 5.2 on 2025-05-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasy', '0005_pointlist_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointlist',
            name='backgroundImage',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='trasy.backgroundimage'),
        ),
    ]
