# Generated by Django 5.2 on 2025-05-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trasy', '0006_alter_pointlist_backgroundimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
