# Generated by Django 5.2 on 2025-05-28 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasy', '0007_delete_route'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rows', models.PositiveIntegerField()),
                ('cols', models.PositiveIntegerField()),
                ('tabel', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('color', models.CharField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dots', to='trasy.gameboard')),
            ],
        ),
    ]
