# Generated by Django 5.2 on 2025-05-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasy', '0009_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='points',
            field=models.JSONField(default=list),
        ),
    ]
